package com.co.brasso.utils.constant

object ApiConstant {

    const val part = "part"
    const val socialLoginUrl = "auth/social-login"
    const val userProfile = "user/profile"
    const val appInfoUrl = "app-info"
    const val bannerUrl = "home"
    const val orchestraUrl = "orchestra"
    const val orchestraDetailUrl = "orchestra/{id}"
    const val playerList = "musician"
    const val orchestraPlayerList = "orchestra-player/{id}"
    const val playerDetail = "musician/{id}"
    const val addFavourite = "orchestra-favourite"
    const val addSessionFavourite = "favourite-orchestra-musician"
    const val myFavourite = "my-favourite-orchestra"
    const val myFavouriteSession = "my-favourite-orchestra-musician"
    const val searchSession = "session-list"

    //constants
    const val grantTypeRefreshToken = "refresh_token"
    const val contentTypeJson = "application/json"
    const val grantTypeSocial = "social"
    const val grantTypePassword = "password"
    const val typeFacebook = "facebook"
    const val typeTwitter = "twitter"
    const val typeLine = "line"
    const val logIn = "auth/login"
    const val register = "auth/register"
    const val getOTP = "auth/send-activation-token"
    const val forgotPassword = "auth/forgot-password"
    const val resetPassword = "auth/reset-password"
    const val tokenVerification = "auth/token-verification"
    const val changePassword = "auth/change-password"
    const val resendToken = "auth/resend-activation-token"
    const val updateProfile = "user/profile"
    const val updateProfilePic = "user/profile-image"
    const val emailPasswordUpdate = "auth/set-password"
    const val registerFcm = "register-fcm"
    const val unRegisterFcm = "unregister-fcm"
    const val bundleList = "bundle-list"
    const val freePointList = "free-point-list"

    const val musicianFavourite = "favourite-musician"
    const val myFavouriteMusician = "my-favourite-musician"

    const val notification = "notification"
    const val notificationDetail = "notification/{id}"
    const val googlePay = "google-pay"

    const val token = "token"
    const val authorization = "Authorization"
    const val id = "id"

    const val clientIdKey = "client_id"
    const val clientSecretKey = "client_secret"
    const val username = "username"
    const val password = "password"
    const val profileImage = "profile_image"
    const val email = "email"
    const val gender = "gender"
    const val dob = "dob"
    const val shortDescription = "short_description"
    const val professionalId = "professional_id"
    const val postalCode = "postal_code"
    const val name = "name"
    const val musicInstrument = "music_instrument"
    const val musicianId = "musician_id"
    const val hallSound = "hall_sound"
    const val conductor = "conductor"
    const val session = "session"
    const val sessionType = "session_type"
    const val page = "page"
    const val keyword = "keyword"
    const val sessionLayout = "orchestra-layout/{id}"
    const val recording = "recording"
    const val orchestraPurchase = "orchestra-purchase"
    const val cartList = "cart-item"

    const val bundlePurchase = "bundle-purchase"
    const val addToCart = "cart-item"

    const val deleteCartItem = "delete-cart-item/{id}"
    const val purchaseCartItem = "orchestra-purchase"

    const val searchOrchestra = "orchestra-search"

    const val instrumentDetail = "instrument-detail/{instrument_id}"
    const val multiPartList = "orchestra-instrument-list/{orchestra_id}"
    const val instrumentId = "instrument_id"
    const val orchestraId = "orchestra_id"
    const val title = "title"
    const val recordingDate = "recording_date"
    const val duration = "duration"
    const val recordingFile = "file"
    const val withdraw = "withdrawal"
    const val errorWhileFetchingPurchases = "Error while fetching purchases"
    const val videoSupport="video_support"
    const val hdSupport="1080p"
    const val fourKSupport ="4k"
    const val notificationPermission="notification/toggle-notification-status"
    const val updateDownloadCount="download-count"

}